name: IaC-Cost-Security-Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 3. Terraform Init & Validate
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # 4. Terraform Plan (JSON output for Infracost & Conftest)
      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Convert Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      # 5. Infracost Breakdown/Diff
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run Infracost
        run: infracost diff --path=tfplan.json --format=json --out-file=infracost.json

      # 6. Conftest Policy Check (OPA)
      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Conftest on Infracost JSON
        run: conftest test infracost.json --policy ./policy

      # 7. Post Cost Report as PR Comment
      - name: Post Infracost Comment
        uses: infracost/actions/comment@v2
        with:
          path: infracost.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
